shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - semver@6.3.1
  - mermaid@10.9.3
packages:
  - apps/*
  - packages/*
catalogs:
  core:
    '@ant-design/cssinjs': ^2.0.3
    '@ant-design/icons': ^6.1.0
    '@excalidraw/excalidraw': ^0.18.0
    '@lexical/react': ^0.39.0
    '@lexical/rich-text': ^0.39.0
    '@lexical/selection': ^0.39.0
    '@lexical/utils': ^0.39.0
    '@tanstack/react-query': ^5.90.20
    '@tanstack/react-router': ^1.157.15
    '@yunzhen/request': ^1.0.1
    antd: ^6.2.2
    clsx: ^2.1.1
    es-toolkit: ^1.44.0
    lexical: ^0.39.0
    motion: ^12.29.2
    react: ^19.2.3
    react-dom: ^19.2.3
    slate: ^0.123.0
    slate-history: ^0.113.1
    slate-react: ^0.123.0
    tailwind-merge: ^3.4.0
    tldraw: ^4.3.0
    type-fest: ^5.4.1
    zustand: ^5.0.10
  dev:
    '@antfu/eslint-config': ^7.2.0
    '@changesets/cli': ^2.29.8
    '@commitlint/cli': ^20.3.1
    '@commitlint/config-conventional': ^20.3.1
    '@commitlint/types': ^20.3.1
    '@eslint-react/eslint-plugin': ^2.7.4
    '@tailwindcss/vite': ^4.1.18
    '@tanstack/react-router-devtools': ^1.157.15
    '@tanstack/router-plugin': ^1.157.15
    '@types/node': ^25.0.10
    '@types/react': ^19.2.9
    '@types/react-dom': ^19.2.3
    '@vitejs/plugin-react': ^5.1.2
    cross-env: ^10.1.0
    eslint: ^9.39.2
    eslint-plugin-format: ^1.3.1
    eslint-plugin-react-hooks: ^7.0.1
    eslint-plugin-react-refresh: ^0.4.26
    lint-staged: ^16.2.7
    rollup-plugin-visualizer: ^6.0.5
    simple-git-hooks: ^2.13.1
    tailwindcss: ^4.1.18
    turbo: ^2.7.6
    tw-animate-css: ^1.4.0
    typescript: ~5.9.3
    unplugin-auto-import: ^21.0.0
    vite: ^7.3.1
    vite-plugin-html: ^3.2.2
    vitest: ^4.0.18
