shellEmulator: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - 'semver@6.3.1'

packages:
  - apps/*
  - packages/*

catalogs:
  dev:
    '@antfu/eslint-config': ^6.7.3
    '@changesets/cli': ^2.29.8
    '@commitlint/cli': ^20.3.1
    '@commitlint/config-conventional': ^20.3.1
    '@commitlint/types': ^20.3.1
    '@tailwindcss/vite': ^4.1.18
    '@types/node': ^24.10.7
    '@types/react': ^19.2.5
    '@types/react-dom': ^19.2.3
    '@vitejs/plugin-react': ^5.1.2
    '@vue/tsconfig': ^0.8.1
    cross-env: ^10.1.0
    eslint: ^9.39.2
    eslint-plugin-format: ^1.2.0
    lint-staged: ^16.2.7
    rollup-plugin-visualizer: ^6.0.5
    simple-git-hooks: ^2.13.1
    tailwindcss: ^4.1.18
    turbo: ^2.7.4
    tw-animate-css: ^1.4.0
    typescript: ~5.9.3
    unplugin-auto-import: ^20.3.0
    vconsole: ^3.15.1
    vite: ^7.2.4
    vite-plugin-html: ^3.2.2
    vitest: ^4.0.16
  integrations:
    react: ^19.2.3
    react-dom: ^19.2.3
