shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - semver@6.3.1
  - mermaid@10.9.3
  - undici-types@6.21.0
packages:
  - apps/*
  - packages/*
catalogs:
  core:
    '@ant-design/cssinjs': 2.0.3
    '@ant-design/icons': 6.1.0
    '@atlaskit/pragmatic-drag-and-drop': ^1.7.7
    '@atlaskit/pragmatic-drag-and-drop-auto-scroll': ^2.1.5
    '@atlaskit/pragmatic-drag-and-drop-flourish': ^2.0.12
    '@atlaskit/pragmatic-drag-and-drop-hitbox': ^1.1.0
    '@atlaskit/pragmatic-drag-and-drop-live-region': ^1.3.3
    '@atlaskit/pragmatic-drag-and-drop-react-accessibility': ^2.2.5
    '@atlaskit/pragmatic-drag-and-drop-react-drop-indicator': ^3.2.12
    '@lexical/react': 0.40.0
    '@lexical/rich-text': 0.40.0
    '@lexical/selection': 0.40.0
    '@lexical/utils': 0.40.0
    '@tanstack/react-query': 5.90.20
    '@tanstack/react-router': 1.158.0
    '@tanstack/react-virtual': ^3.13.19
    '@yunzhen/request': 1.0.1
    antd: 6.2.3
    clsx: 2.1.1
    es-toolkit: 1.44.0
    lexical: 0.40.0
    motion: 12.31.0
    react: 19.2.4
    react-dom: 19.2.4
    react-responsive: ^10.0.1
    slate: 0.123.0
    slate-history: 0.113.1
    slate-react: 0.123.0
    tailwind-merge: 3.4.0
    tldraw: 4.3.1
    type-fest: 5.4.3
    zustand: 5.0.11
  dev:
    '@antfu/eslint-config': ^7.2.0
    '@changesets/cli': ^2.29.8
    '@commitlint/cli': ^20.4.1
    '@commitlint/config-conventional': ^20.4.1
    '@commitlint/types': ^20.4.0
    '@eslint-react/eslint-plugin': ^2.9.4
    '@rsbuild/plugin-react': ^1.4.5
    '@rslib/core': ^0.19.4
    '@rspress/core': ^2.0.2
    '@tailwindcss/vite': ^4.1.18
    '@tanstack/react-router-devtools': ^1.158.0
    '@tanstack/router-plugin': ^1.158.0
    '@types/node': ^25.0.10
    '@types/react': ^19.2.11
    '@types/react-dom': ^19.2.3
    '@vitejs/plugin-react': ^5.1.3
    cross-env: ^10.1.0
    eslint: ^9.39.2
    eslint-plugin-format: ^1.3.1
    eslint-plugin-react-hooks: ^7.0.1
    eslint-plugin-react-refresh: ^0.4.26
    lint-staged: ^16.2.7
    react-grab: ^0.1.14
    react-scan: ^0.4.3
    rollup-plugin-bundle-stats: ^4.21.9
    rollup-plugin-visualizer: ^6.0.5
    simple-git-hooks: ^2.13.1
    tailwindcss: ^4.1.18
    turbo: ^2.8.3
    tw-animate-css: ^1.4.0
    typescript: ~5.9.3
    unplugin-auto-import: ^21.0.0
    vite: ^7.3.1
    vite-plugin-html: ^3.2.2
    vitest: ^4.0.18
